Python3
visgence/timeclock pull request #12
Opened 2023-09-07 20:53 UTC by patrickpritchett

This PR updates Docker linux version to Alma 9, postgres to 11 and fixes some errors. Updates for logo and disable Job functionality also included.

**NOTE** Revert `.gitmodules` -> branch after Chucho python3 branch is merged to master.

**Files Changed**

`.gitmodules`

- updated url
- TEMP branch specification

`docker/app/Dockerfile`
`docker/app/pip-requirements.txt`
`docker/postgres/run.sh`
`requirements.txt`

- docker and postgres updgrades

`time_system/clocker/hashMethods.py`

- fixed error by adding encode and str() cmds

`time_system/clocker/models.py`

- fixed error for ManyToManyField error by using .set() vs =
- added default hourly_rate of 0.00 when not set

`time_system/clocker/views/job.py`

- added default hourly_rate and miles of 0.00 when not set

`time_system/clocker/views/timesheet.py`

- removed duplicate `employee` entry from return dict

`time_system/clocker/templates/base.html`
`time_system/clocker/templates/mainPage.html`
`time_system/clocker/templates/manageShifts.html`
`time_system/clocker/views/mainPage.py`
`time_system/urls.py`

- added conditions for ENABLE_JOBS

`time_system/clocker/views/shiftExport.py`

- added conditions for ENABLE_JOBS
- added message when no results

`time_system/clocker/views/clockEmployee.py`

- added condition to auto save summary to default(id=1) job

`time_system/clocker/static/js/timeline.js`

- replaced hard coded visgence.com with relative url

`time_system/clocker/static/images/logo.png`
`time_system/clocker/static/images/Visgence_incwhite.png`

- renamed image

`time_system/clocker/management/commands/setup.py`

- updated to load default job when jobs disabled and running ./manage.py setup

`time_system/settings.py`

- added DEFAULT_AUTO_FIELD to squash warnings
- added ENABLE_JOBS flag

`README.md`

- Added notes for new job functionality and branding

2025-02-12 05:08 UTC, shiftycow requested changes
Change request from meeting today:
Update the "check_db" script to:
if a shift is found to go over midnight:
   - set the clock_out time to 23:59:59
   - delete assocaited shift summaries

Cases that need to be considered:
- clock out time is a different day that clock in
- clock in time is the day before the script is run
   - if we run the script with cron, someone might still be clocked in when the script is run. 

Don't worry about setting a cron job, just change how the script works but leave the trigger the same. we can make another PR to change the trigger condition

2025-02-12 18:18 UTC, shiftycow commented on time_system/check_db.py
> +            shift_summary.delete()
Seems like this will delete every shift summary in the DB, no?

2025-02-12 18:31 UTC, patrickpritchett commented on time_system/check_db.py
> +            shift_summary.delete()
It is all in a loop called from `main()`, one record at a time. Then the `get` retrieves the one summary with the matching shift id and deletes it.

2025-02-12 18:35 UTC, shiftycow commented on time_system/check_db.py
> +            shift_summary.delete()
that loop runs over every Shift in the DB:

```
def main():

    for record in Shift.objects.all():
        correct_record(record)
```

Checking for whether there is a problem isn't done until :37, which is after the delete happens.

2025-02-12 18:37 UTC, shiftycow commented on time_system/check_db.py
> +            shift_summary.delete()
And furthermore, it only gets one record. If there were multiple shift summaries, it would throw an exception. I think that would be a rare edge case, but might as well handle it.

2025-02-17 19:02 UTC, shiftycow approved these changes
Seems to work OK. I tried some scenarios for `check_db` and it seems to be working ok, too:
- created a "normal" shift with summaries
- created a shift that spanned over midnight (clocked in and clocked out on separate days) and had summaries
- created a shift that started yesterday and was not clocked out

check DB did what I expected. Did not affect the normal shift, set the second to end at 23:59 and deleted the summaries, and set the third to be clocked out at 23:59.

2025-03-10 20:50 UTC, senormeow requested changes
Something is wrong with milage totaling 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/timeclock/timeclock/time_system/time_system/clocker/views/job.py", line 51, in jobBreakdown
    miles += j.miles if j.miles else 0.00
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'

```

2025-04-07 22:13 UTC, merged